models:
  - class: "RandomForestClassifier"
    module: "sklearn.ensemble"
    params:
      n_estimators: 50

  - class: "KNeighborsClassifier"
    module: "sklearn.neighbors"
    params:
      n_neighbors: 3

  - class: "XGBClassifier"
    module: "xgboost"
    params:
      n_estimators: np.arange(50, 201, 50)
      max_depth: [4, 6, 8]
      learning_rate: [0.001, 0.01, 0.1, 1]